language: go

go:
  - 1.9.2

script:
- go test -race -v ./...
- go test -race -tags="debug" -v
- go test -race -tags="trace" -v -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
